site_name: Bookseller Services Systemhandbuch
site_dir: target/site/docs/systemhb
docs_dir: src/main/docs
pages:
 - [index.md, Home]
 - [architecture.md, Architekturhandbuch]
 - [coding.md, Programmierhandbuch]
 - [api.md, API-Handbuch]
 - [glossary.md, Glossar]